### ISSUE TITLE
Update example.spec.ts to contain more examples

### ISSUE THREAD

**Issue by willemneal** [jtenner/as-pect#107]
Currently [example.spec.ts](../blob/master/init/example.spec.ts) only has a single function.  Having more examples is a good way to help new users get started.

**Comment by jtenner** [comment]
@trusktr might like to pick up some of the slack.

**Comment by jtenner** [comment]
Things that would be great.

- [ ] Custom error messages (via assertion functions)
- [ ] String Comparison
- [ ] Reference comparison (using a vector?)
- [ ] Array of numbers comparison
- [ ] toBeTruthy
- [ ] negation using `.not`
