### ISSUE TITLE
[Docs] Add reasons to use as-pect over typical testing frameworks for AssemblyScript

### ISSUE THREAD

**Issue by jtenner** [jtenner/as-pect#164]

**Comment by jtenner** [comment]
Mentioned in https://github.com/AssemblyScript/assemblyscript/issues/977

**Comment by MaxGraey** [comment]
One potential reason which I see is as-pect could be independent on node.js in future and using wasi instead

**Comment by ColinEberhardt** [comment]
It would also be interesting to see how as-pest integrates with blockchains using wasm, NEAR protocol for example.

**Comment by MaxGraey** [comment]
As I know as-pect used in NEAR protocol

**Comment by jtenner** [comment]
I believe @willemneal is going to be responsible for integrating as-pect into near studio some time in the future.

Currently, near uses as-pect to test their AssemblyScript runtime. I have accepted some pull requests to aid in their development cycles.
