### ISSUE TITLE
expect().toBe(null), but ironically compile error is "Object is possibly 'null'."

### ISSUE THREAD

**Issue by trusktr** [jtenner/as-pect#165]
I've got an error like 

```
ERROR TS2531: Object is possibly 'null'.

                ).toBe(null)
          ~~~~
```

Over here: https://github.com/infamous/glas/compare/EventDispatcher-tests?expand=1#diff-5235e729a0a829f289a7eddd3ad7742fR94

The code is 

```ts
		expect<Array<Listener>>(
			// prettier-ignore
			// @ts-ignore: private access
			eventDispatcher._listeners
					.get('unknownType')!
		).toBe(null)
```

I think I may have asked this before, but it's been a while. How to test it to be null?

**Comment by jtenner** [comment]
The expect type is not nullable and therefore it's impossible to be null.

Use

```ts
expect<Array<Listener> | null>(
```

**Comment by trusktr** [comment]
Ah, ok, makes sense!
