### ISSUE TITLE
Failing on CircleCI due to process.stdout.columns being 0

### ISSUE THREAD

**Issue by s1na** [jtenner/as-pect#170]
Hello :wave:

I'm trying to set-up as-pect for our project but faced an issue when running tests in CI. Apparently CircleCI sets `process.stdout.columns` to 0 and causes this [line](https://github.com/jtenner/as-pect/blob/00c4d1aad740d52a9a26653f41efe227ed2eaa44/packages/cli/src/run.ts#L426) to fail. If you see the ci [logs](https://circleci.com/gh/ewasm/biturbo/76) of https://github.com/ewasm/biturbo/pull/48 I tried printing out the `columns` value in the "test node columns" job, and the resulting error you can see in the "Run assemblyscript tests" job. Please let me know if I can provide any additional information.

**Comment by jtenner** [comment]
It looks like the only things that come to mind involving `process.stdout.columns` might be `chalk` and threaded module execution. I know it fails on the promise line, but we should figure out where the `runBinary` function fails first. I'll have to take a look at this soon.

**Comment by jtenner** [comment]
@willemneal It looks like `String.repeat()` doesn't like it when the argument is `0`. This is something I hadn't expected.
