### ISSUE TITLE
Quotation in expected field

### ISSUE THREAD

**Issue by willemneal** [jtenner/as-pect#2]
A test like:
```ts
expect<bool>(false).toBeTruthy();
```
returns the following message.
```
 [Actual]: 0
 [Expected]: "truthy
```

**Comment by jtenner** [comment]
Actual expected message should be

```
 [Actual]: 0
 [Expected]: truthy
```

**Comment by willemneal** [comment]
Also just a styling issue: it would be nice if the values were lined up.
```
      [Actual]: 0
 [Expected]: truthy
```

**Comment by jtenner** [comment]
This should be fixed. Closing for now. Feel free to open a new issue if formatting becomes a problem
