### ISSUE TITLE
[Feature] Pass node options

### ISSUE THREAD

**Issue by willemneal** [jtenner/as-pect#200]
In my current project, I need to invoke an experimental flag in node.  After some digging I found that node provides an interface for setting those options:

```js
const v8 = require('v8');
v8.setFlagsFromString('--experimental-wasm-bigint');
```

So it's trivial to add this to a user's as-pect.config.js, but it would be nice if it was just another configuration option/cli option.

**Comment by jtenner** [comment]
This can technically be done in the config by just requiring v8 inside the config file. Right?

**Comment by jtenner** [comment]
Maybe the solution is just to document this in the gitbook and encouraging our users to enable v8 flags in their configurations manually.
