### ISSUE TITLE
Is there any way to do module import mocking like in jest?

### ISSUE THREAD

**Issue by JasoonS** [jtenner/as-pect#209]
Hi, I would like to be able to mock various modules in my tests similar to how jest does it (https://jestjs.io/docs/en/manual-mocks). Is there any way to do this?

Thanks

**Comment by jtenner** [comment]
This is possible. Technically. We can slate some kind of feature for a later date.

@willemneal could this be possible via a transform?

**Comment by willemneal** [comment]
@JasoonS Do you mean modules from the stdlib or generally?  If it's the former, you can choose to not compile with the stdlib and instead provide your own, which you can use the `--lib` option to force the compiler to read in all the files in the folder you want to include. The reason for this is that stdlib classes, etc are global and require the `@global` decorator.  This means that entry files don't need to import them rather the compiler just have to have read them.  `as-pect` uses this too with our global definitions, however, it adds an additional entry file, which the compiler treats as a user entry file and not a library.  Though I'm not sure what the distinction means, but they do get marked differently.

**Comment by jtenner** [comment]
It's entirely possible to do a source transformation for modules:

```ts
import { thing } from "module";
```

And turn it into...

```ts
import { thing } from "module-mock";
```

at compile time.

**Comment by willemneal** [comment]
Yeah, we could also have a mock folder and then anything in it will overwrite the definitions of any already defined class.

**Comment by jtenner** [comment]
Right now I'm refactoring log/actual/expected value reporting, so this will take back seat, but if you want to try and take a look after the huge refactor, we can tackle this reasonably and ask for advice.

**Comment by willemneal** [comment]
Sounds good.

**Comment by JasoonS** [comment]
(sorry for the late reply @willemneal )

My use case is simple, I want to add tests to this project: https://github.com/wild-cards/subgraph

I was wondering about mocking because https://thegraph.com generates quite a bit of code based on your config, and it would be very nice to be able to mock them for your test.

But I think for now my 'lo-tech' solution is to replace the folder with the generated files with my mocks just before the tests run, and then regenerating the files after the tests. (so this isn't blocking me or anything, just think it's a cool feature)

Great stuff guys! :pray: I'm looking forward to using this library more!

**Comment by jtenner** [comment]
@JasoonS I have to table this request for module mocking until later because I have to refactor the entire test collection algorithm. I already have a game plan though, and I will make sure this gets into play by version `4.0.0`.

**Comment by jtenner** [comment]
Alright. Here's how you can do module mocking.

```js
module.exports = {
  ..., // the rest of your config
  flags: {
    "--lib": "assembly/mocks"
  }
}
```

Then in an `assembly/mocks` folder, create a file for each module you would like to mock.

For instance:

```ts
// ./assembly/mocks/add.ts

export function add(a: i32, b: i32): i32 {
  return a + b;
}
```

Then anywhere your code requires `add`:

```ts
import { add } from "add";
``` 

Please advise if this works as intended? Thanks!
