### ISSUE TITLE
inline arrays have leading commas

### ISSUE THREAD

**Issue by DuncanUszkay1** [jtenner/as-pect#228]
When we have the following code:
```
expect<Array<i32>>([1,2,3]).toBe([3,4,5])
```
We get this output:
```
❌ assembly/__tests__/example.spec.ts Pass: 0 / 1 Todo: 0 Time: 4.388ms
  Failed: example
    ❌ should display the override method -
      [Expected]: Array<i32> [3, 4, 5, ]
      [Actual]  : Array<i32> [1, 2, 3, ]
```
This output has an extra comma which ought to be removed. The intended output looks like this:
```
❌ assembly/__tests__/example.spec.ts Pass: 0 / 1 Todo: 0 Time: 4.388ms
  Failed: example
    ❌ should display the override method -
      [Expected]: Array<i32> [3, 4, 5]
      [Actual]  : Array<i32> [1, 2, 3]
```

**Comment by jtenner** [comment]
The problem is here:

https://github.com/jtenner/as-pect/blob/master/packages/core/src/util/stringifyReflectedValue.ts#L427

We need to account for the last item not having a `", "` appended, or we can just append `", "` to the beginning of each value as long as it isn't the first one.
