### ISSUE TITLE
Snapshot testing for VerboseReporter  and SummaryReporter

### ISSUE THREAD

**Issue by 9oelM** [jtenner/as-pect#240]
- [ ] Create a generic module to test stdout  (in jest test, we can bootstrap our own stdout and snapshot the output)
- [ ] Make sure chalk is disabled and doesn't output ansii, or strip ansii from result
- [ ] Loop over each test and log item, snapshot each individual group and test

**Comment by jtenner** [comment]
I'm starting to think that we should make reporter output configurable with format functions.
