### ISSUE TITLE
How to test methods that make WASI calls?

### ISSUE THREAD

**Issue by jeffcharles** [jtenner/as-pect#246]
Given a file `sample.ts`:

```typescript
import { Console } from "as-wasi";

export function sample(): void {
    Console.log("Foo");
}
```

and a test file `sample.spec.ts`:

```typescript
import { sample } from "../src/sample";

describe("sample", () => {
  it("Should verify something", () => {
    sample();
  });
});
```

I get:
```
TypeError: WebAssembly.Instance(): Import #1 module="wasi_unstable" error: module is not an object or function
    at instantiateSync (/Users/jeffreycharles/scripts/feb27/node_modules/assemblyscript/lib/loader/index.js:307:5)
    at runBinary (/Users/jeffreycharles/scripts/feb27/node_modules/@as-pect/cli/lib/run.js:366:28)
    at /Users/jeffreycharles/scripts/feb27/node_modules/@as-pect/cli/lib/run.js:482:46
    at Object.main (/Users/jeffreycharles/scripts/feb27/node_modules/assemblyscript/cli/asc.js:775:10)
    at /Users/jeffreycharles/scripts/feb27/node_modules/@as-pect/cli/lib/run.js:433:21
    at Array.forEach (<anonymous>)
    at run (/Users/jeffreycharles/scripts/feb27/node_modules/@as-pect/cli/lib/run.js:431:40)
    at Object.asp (/Users/jeffreycharles/scripts/feb27/node_modules/@as-pect/cli/lib/index.js:72:13)
    at Object.<anonymous> (/Users/jeffreycharles/scripts/feb27/node_modules/@as-pect/cli/bin/asp:2:28)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
```

How can I configure `as-pect` so that the `Console.log` call works in the test? Ideally that it prints `Foo` to stdout, less ideally, that the test executes successfully.

**Comment by jtenner** [comment]
This will be fixed in the next version of the AssemblyScript loader. `as-pect` doesn't need to have an opinion on WASI usage, but we can add a cli `--init-wasi` to setup a default configuration file that instantiates a `WASI` instance in node inside the config.

**Comment by jtenner** [comment]
This feature is slated for 3.2.0. This is because the `WASI` instance is required when calling the `_start()` function to setup the memory hooks.

We will need to have `as-pect` be responsible for calling that function in the `visit(node)` function.

**Comment by jtenner** [comment]
Hey. So this is now finally being resolved with version 0.10.

Are you available for testing soon? I am going to release `as-pect` version 4.0 to npm, and it should have `wasi` support.

```ts
//as-pect.config.js
module.exports = {
  wasi: {
    // node wasi options go here
  }
}
```

I am going to need some kind of help with this to validate that it works.

**Comment by jeffcharles** [comment]
The earliest I’ll be able to look at this is Tuesday. We have a statutory holiday on Monday and I have today off.

**Comment by jtenner** [comment]
Looks like I actually found a bug in node's wasi implementation. This should be ready by Tuesday.
