### ISSUE TITLE
toStrictEquals on extended classes

### ISSUE THREAD

**Issue by DuncanUszkay1** [jtenner/as-pect#250]
toStrictEquals uses the Reflect module to provide object traversal equality. However, two objects differ only in fields that exist on their parent classes, this comparison will return true.

For Example:
```typescript
@unmanaged class Parent {
  id: u32
  constructor(x: i32) {
    this.id = x
  }
}
@unmanaged class Child extends Parent {
  static from(x: i32): Child { return <Child>(new Parent(x)) }
}
describe("Child", () => {
    it("children with different ids dont strict equal", () => {
        expect<Child>(Child.from(2)).toStrictEqual(Child.from(1));
    });
});
```
This test should not pass, but does.

**Comment by jtenner** [comment]
Yes this is something I did not forsee. Anything with a parent class has their parent property comparisons completely ignored.

I'm order to fully support this feature we need to resolve the class type and inspect the members of that class type. 

This requires that the program be instantiated and that the resolver can resolve the class. (This cannot be done currently with the limitations provided by assemblyscript transforms currently.)

We will have wait for @dcode to help provide a proper transform hook for this to be possible.

In the meantime, implementing all the parent properties in your child classes will fix this.

**Comment by jtenner** [comment]
Please see https://github.com/AssemblyScript/assemblyscript/issues/1142 for more information.

**Comment by jtenner** [comment]
This is all set. I ended up making a custom solution to call `super.__aspectStrictEquals()` and avoid comparing overridden properties using a `string[]` parameter.
