### ISSUE TITLE
Should csv-stringify be a required dependency?

### ISSUE THREAD

**Issue by jeffcharles** [jtenner/as-pect#257]
I ran into an interesting case today where I attempted to run `asp` with a configuration that doesn't reference CSVs but got an error saying `Error: Cannot find module 'csv-stringify'`. Looking more into it, I realized that `csv-stringify` wasn't installed by NPM (happens with NPM 5.x but not NPM 6.x) which seemed fair because `csv-stringify` is listed as an optional dependency. In the source TS code, it looks like a safe call to have `csv-stringify` be optional however in the JS code that it compiles to, it appears to unconditionally require `csv-stringify`.

**Comment by jtenner** [comment]
@9oelM and I are working on getting `tsc` to cooperate and work with parcel and webpack. Each module is currently transpiled to `es5` modules, and I'm just not certain how things should work.

This seems like something we should definitely fix.
