### ISSUE TITLE
TS2304 compilation errors when using 'describe' scoped variables

### ISSUE THREAD

**Issue by alexvictoor** [jtenner/as-pect#281]
Hello
First, thanks for your work on as-pect.
I am quite an assemblyscript newbie, I am not sure this is a real as-pect issue but when I declare a variable inside a describe block I cannot use it inside a testcase function:
```
describe("....", () => {
   const value: u8 = 42;
   it("should work", () => {
    expect<u8>(value).toBe(40 + 2);
   });
```
I get a compilation error as below: 
```
ERROR TS2304: Cannot find name 'value'.
     expect<u8>(value).toBe(40 + 2);
```

**Comment by DuncanUszkay1** [comment]
This is likely due to https://github.com/AssemblyScript/assemblyscript/issues/798

**Comment by jtenner** [comment]
There is currently no closure support. This is correct.

**Comment by alexvictoor** [comment]
Thanks!
I guess I was mistaken by the code example at the bottom of the getting started page: https://tenner-joshua.gitbook.io/as-pect/getting-started

**Comment by jtenner** [comment]
You can enclose over global variables.

**Comment by jtenner** [comment]
Closed stale. Feel free to reopen if there's issues.

**Comment by jtenner** [comment]
I
