### ISSUE TITLE
StrictEquality print depth

### ISSUE THREAD

**Issue by DuncanUszkay1** [jtenner/as-pect#282]
Right now when you compare two deeply nested objects, the logged result is truncated. Consider the following example:
```typescript
class LayerA {
  parent: LayerB
}
class LayerB {
  parent: LayerC
}
class LayerC {
  parent: LayerD
}
class LayerD {
  foo: i32
}
describe("example", () => {
  it("should print as expected", () => {
    let nested: LayerA = {
      parent: {
        parent: {
          parent: {
            foo: 7
          }
        }
      }
    }
    let wrongNested: LayerA = {
      parent: {
        parent: {
          parent: {
            foo: 20
          }
        }
      }
    }
    expect<LayerA>(nested).toStrictEqual(wrongNested);
  });
});
```
outputs 
```
┃ ❌ test/script.spec.ts Pass: 0 / 1 Todo: 0 Time: 6.548ms
┃   Failed: example
┃     ❌ should print as expected -
┃       [Actual]  : LayerA {
┃       parent: LayerB {
┃           parent: LayerC {
┃               parent: [LayerD]
┃           }
┃       }
┃   }
┃       [Expected]: LayerA {
┃       parent: LayerB {
┃           parent: LayerC {
┃               parent: [LayerD]
┃           }
┃       }
┃   }
```
Which hides the foo field.

**Comment by jtenner** [comment]
I'm not sure how to fix this, and traversal depth is a feature by design to prevent deeply nested objects from flooding stdout.

I'm open to suggestions, however.

**Comment by DuncanUszkay1** [comment]
Would it make sense to print out the full object (barring circular references) in verbose mode? If I'm comparing two large objects in a test in verbose mode, and I get a lot of output, is that a problem?

We would have to deal with circular references in this case, though given that there's already a similar algorithm implemented to do the comparison it seems that should be doable.

Thoughts?

**Comment by jtenner** [comment]
Circular references are already handled in `Reflection.toReflectedValue()`. But you make a very good point. I will be sure to include this in the breaking changes for 4.0.
