### ISSUE TITLE
strange error: env: node\r: No such file or directory

### ISSUE THREAD

**Issue by alexvictoor** [jtenner/as-pect#295]
I have just tried to upgrade as-pect to version 3.2.0. 
When launching asp I get a strange error: **env: node\r: No such file or directory**
I am using assemblyscript 0.10 and node 12.11.1
Thanks a lot for your help

**Comment by jtenner** [comment]
Are you using wasi?

**Comment by alexvictoor** [comment]
I do not.
If it is helpful, my code (without the versions bumped) is here: https://github.com/alexvictoor/HdrHistogramJS

**Comment by jtenner** [comment]
Promise I will get around to looking at this soon. With major language updates, errors are bound to happen.

**Comment by alexvictoor** [comment]
No rush. Again, thanks a lot for your work on as-pect!

**Comment by jtenner** [comment]
Okay. So here's what I did locally. I used npm install, but I suspect this error might have something to do with yarn.

```ts
{
  "dependencies": {
    "@as-pect/cli": "^3.2.0", // dev dependency
    "assemblyscript": "^0.10.0", // dev dependency
    "@assemblyscript/loader": "^0.10.0"
  }
}
```

Then I ran `astest`.

Seems like everything is working as intended.

Not sure how to reproduce this error?

**Comment by jtenner** [comment]
Oh. I forgot to use node 12. Just a moment.

**Comment by jtenner** [comment]
Alright. I have redrun the astest script, using `12.16.3`. I believe your error *may* be related to your node version.

I also think it may be wise to upgrade all your package versions by deleting your yarn.lock, updating the package versions, and re-running yarn.

**Comment by alexvictoor** [comment]
Hi again, the problem does not seem to be related to node but to yarn.
I have switched to node 12.16.3.
If I install all the dependencies from scratch using "npm install" everything is fine. However if I install all the dependencies using yarn I get the weird error.
I have no clue why yarn behave this way...

**Comment by jtenner** [comment]
Have you tried deleting your yarn lock and generating a new lock file? Refreshing your dependencies helps sometimes.

**Comment by alexvictoor** [comment]
I have just tried again and now I get a new error when I delete my yarn lock and the node modules:
```
yarn run v1.19.0
$ asp --verbose
/Users/alexandrevictoor/.nvm/versions/node/v12.16.3/bin/node: bad option: --experimental-wasm-bigint
```

I have also tried again to perform an 'npm install' after having deleted my package-lock and the node modules. It works fine with npm...

**Comment by jtenner** [comment]
So it works fine with npm but it fails with yarn? 🙃

**Comment by jtenner** [comment]
I'm not sure how to handle this one.

**Comment by jtenner** [comment]
```
/usr/bin/env: ‘node --experimental-wasi-unstable-preview1 --experimental-wasm-bigint’: No such file or directory
npm ERR! Test failed.  See above for more details.
```

**Comment by jtenner** [comment]
I've reproduced the problem. Are you using linux? :)

**Comment by alexvictoor** [comment]
I am not using linux but I am using MacOS

**Comment by jtenner** [comment]
https://github.com/jtenner/as-pect/pull/300

Not sure if you can do a code review, but this appears to do the trick. Any chance I could get you to clone the repo and use lerna to bootstrap the modules and test this?

**Comment by alexvictoor** [comment]
@jtenner  sorry for the late response. Of course I am happy to help, I will try to test the fix asap this week

**Comment by alexvictoor** [comment]
I have just tested with the code form the as-pect monorepo, the issue seems to have disappeared! I have just noticed I get the issue on travis-ci with npm / linux... hope you will be able to release the fix soon :)

**Comment by jtenner** [comment]
@alexvictoor I believe the fix is already live on npm via version `3.2.3`

**Comment by alexvictoor** [comment]
Well the good news is that my travis ci build is fixed with as-pect 3.2.3 :
https://travis-ci.org/github/alexvictoor/HdrHistogramJS
However on my laptop, I still reproduce the issue when I install the dependencies using yarn instead of npm. This is not a big deal, I have switched to npm, but still this is really weird...

**Comment by alexvictoor** [comment]
I guess this is a yarn issue: https://stackoverflow.com/a/52785600

**Comment by jtenner** [comment]
@alexvictoor I suggest deleting `node_modules` and `yarn.lock` and trying again.

**Comment by alexvictoor** [comment]
@jtenner I am already deleting node_modules and yarn.lock each time I try something. 
I have even tried to convert my package)lock.json file to yarn.lock using 'yarn import'. That does not work.
I really thing this is a yarn issue, the one that is mentioned in the previous stackoverflow thread:

https://github.com/yarnpkg/yarn/issues/5480

**Comment by jtenner** [comment]
Okay. I suppose this can't be fixed then. Thanks for your help.
