### ISSUE TITLE
Strict equality of types with different fields

### ISSUE THREAD

**Issue by maximebedard** [jtenner/as-pect#313]
Hi! I'm running into an issue where fields on subclasses are different. Even by implementing a custom `==`, I'm running into issues when trying to use `toBe` or `toStrictEqual`. I have the following:

```ts
abstract class A {
  foo(): f32 { throw new Error("unexpected"); }
  bar(): f32 { throw new Error("unexpected"); }
}

class B extends A {
  readonly v: f32;
  foo(): f32 { return this.v; }
}

class C extends A {
  readonly v: u32; 
  foo(): u32 { return this.v; }
}
```

Using `expect(<B>{ v: 42 }).toStrictEqual(<C>{ v: 42 });` would yield the following errors:

```
ERROR TS2339: Property 'v' does not exist on type 'assembly//A'.

   readonly v: f32;
   ~~~~~~~~~~~~~~~~~~~

ERROR TS2339: Property 'v' does not exist on type 'assembly//A'.

   readonly v: u32;
   ~~~~~~~~~~~~~~~
```

I'm guessing the transform is generating code that assumes that all the fields are defined on `A`. Even by overriding `==`, the transform is still trying to generate this code to compare it.  I can go around it by using a simple `assert`, but was wondering if this is expected behaviour?

Thanks!

**Comment by jtenner** [comment]
Virtual comparison is not supported. Strict comparison should match types exactly. 

And yes, this is an unfortunate limitation of the environment.

**Comment by jtenner** [comment]
This is not something as-pect can support. Closing because it's old.
