### ISSUE TITLE
Option to show stack traces from test code

### ISSUE THREAD

**Issue by trusktr** [jtenner/as-pect#318]
Is this a matter of which reporter is used?

At the moment, I see output like this:

```
✔ src/as/core/BufferAttribute.spec.ts Pass: 18 / 18 Todo: 21 Time: 14.351ms
❌ src/as/core/BufferGeometry.spec.ts Pass: 0 / 1 Todo: 8 Time: 4.236ms
  Failed: BufferGeometry
    ❌ setIndex/getIndex - index must have at least one item
  [Result]: ✖ FAIL
   [Files]: 2 total
  [Groups]: 14 count, 14 pass
   [Tests]: 18 pass, 1 fail, 19 total
    [Time]: 1955.497ms
```

where `index must have at least one item` is an error message from a `new Error` that I throw in the class I'm testing. I don't see any stack trace for the error.

**Comment by jtenner** [comment]
Yes. Please use the --verbose reporter.

**Comment by trusktr** [comment]
Oh, interesting.

Would be nice to make it verbose only for failed tests (collapse passed/todo tests)
