### ISSUE TITLE
Strange output when executing toString() on a number

### ISSUE THREAD

**Issue by ColinEberhardt** [jtenner/as-pect#320]
~~~
describe("example", () => {
  it("breaks", () => {
    for (let i = 0; i < 3; i++) {
      log(i.toString());
      log(i);
    }
  });
});
~~~

The above code logs the following:

~~~
✔ assembly/__tests__/example.spec.ts Pass: 1 / 1 Todo: 0 Time: 10.21ms
     [Log]: "0"
     [Log]: 0
     [Log]: "1"
     [Log]: 1
     [Log]: "1"
     [Log]: 2
~~~

In other words, the toString is generating the wrong output on the third iteration!

**Comment by jtenner** [comment]
This might be a compiler issue downstream. Fascinating.

**Comment by jtenner** [comment]
Making this issue more exaggerated makes it look more and more like there's a bug in RTrace.

```ts
✔ assembly/__tests__/example.spec.ts Pass: 1 / 1 Todo: 0 Time: 49.512ms
     [Log]: 0
     [Log]: "0"
     [Log]: 1
     [Log]: "1"
     [Log]: 2
     [Log]: "1"
     [Log]: 3
     [Log]: "1"
     [Log]: 4
     [Log]: "1"
```

What's interesting is that the compiler is likely using the same pointer multiple times, which means that the external `getString()` method uses a cached version of the string.

Even more, when the "1" is released, it refuses to free, which causes that pointer to remain completely cached in that exact spot at that memory location.

Looks like a caching error :)

**Comment by jtenner** [comment]
Indeed this is the case.

```ts
Improper string cache: 2 != 1
Improper string cache: 3 != 2
Improper string cache: 4 != 3
✔ assembly/__tests__/example.spec.ts Pass: 1 / 1 Todo: 0 Time: 85.09ms
     [Log]: 0
     [Log]: "0"
     [Log]: 1
     [Log]: "1"
     [Log]: 2
     [Log]: "2"
     [Log]: 3
     [Log]: "3"
     [Log]: 4
     [Log]: "4"
```

@willemneal is it possible that the `onfree` rtrace method isn't being called correctly?

**Comment by jtenner** [comment]
I can fix this issue by removing string caching, but it's better to solve the downstream problem too.

**Comment by jtenner** [comment]
Found it. Feel free to check out the change in #321 which is very small related to string caching.
