### ISSUE TITLE
High Rtrace values causing test errors?

### ISSUE THREAD

**Issue by torch2424** [jtenner/as-pect#323]
Hello! This might be more of a discussion point, than a bug in as-pect. I'm not too sure, but I'll create a repro case if you think this might be a bug :smile: 

So I'm working on a unit test of an object with a complex constructor. I'm testing a case I expect to throw, and at the end of the test I get: `RTrace: +16`. And this was causing a really weird behavior, where the test would fail, which appeared to be a runtime error. And as-pect would also output:

![Screenshot from 2020-12-11 16-51-31](https://user-images.githubusercontent.com/1448289/101967828-2632d000-3bd1-11eb-95b8-8e59f12e2ff8.png)

---

And for geenral google and github search:

```
[Error]: rtrace: Block: 8940 => shadow region mismatch: 0 != 8940
 [Stack]:     at Rtrace.unmarkShadow

...
```

---

So I'm not too sure what this means, but looking at the docs for RTrace, it meantions is might be a memory leak? https://tenner-joshua.gitbook.io/as-pect/as-api/rtrace-and-memory-leaks

However, the constructor is definitely creating a lot of objects on the runtime, and even runs through a few loops. If I understand the docs correctly, the Rtrace is a report of the number of object that were alive when the function had an error. So, a high Rtrace value (if it's not being cleaned up like the docs mentions), makes sense for this test.

To fix this in the meantime, I just threw the problematic test, as the last test in my describe block, and everything seems to be working fine now :smile: 

Is this something on me? Or is this an as-pect issue? :thinking:

**Comment by jtenner** [comment]
I genuinely *dont* know if it's `as-pect`'s issue either, because as dcode puts it: "These are the hardest kinds of errors to debug."

Context for errors like this: This error happens when a release occurs and attempts to re-clean up memory that has already been cleaned up. I have experienced issues like this, and they are probably related to the compiler still trying to fix it's garbage collector.

The reason why I know this is true, is because the stack trace shows that it called the `onfree()` method at the top of the stack where the error occurred.

Now what's interesting is I had the same issue involved with `Array<String>` too. I'm not entirely sure what is causing the problem, but it may be useful to figure out what exists at memory region `8940`. 

Is there a way you can figure that out?

**Comment by jtenner** [comment]
Also in regards to the high RTrace values. `+16` is probably indicative that a memory leak occurred and left 16 references on the stack before the function execution halted and unwound the stack. This is indicative of a specific problem, rather than 16 specific problems.

**Comment by torch2424** [comment]
@jtenner Ahhhh okay so this does fall into the memory leak problem category :thinking: 

Hmm, I'll play around with how memory is being allocated when I get the chance, and get back to you! :smile:

**Comment by jtenner** [comment]
Chances are, you should be looking for a managed object that doesn't get retained immediately, and then gets released normally. This causes the rogue release problem to occur.

I also think it probably happens near the `new Array<Type>()` constructor, if you use it.

I haven't been able to find it myself.

**Comment by torch2424** [comment]
Ah! So if Array's are causing some trouble, I was doing a string split, and then operating on top of that array in a while loop.

Changing the implementation to not use Arrays, greatly my Rtrace values. And things appear to be throwing less errors due to memory issues :thinking: 

I'll try to make a small reproduction case when I get the chance. :smile:

**Comment by jtenner** [comment]
I'm glad you found the issue. I suspect this is somehow a compiler issue. Just not sure how to isolate it. Any help you can provide will be very useful!

Thanks.

**Comment by jedisct1** [comment]
I'm now seeing tons of similar errors in the `wasm-crypto test`. As well as alignment issues (`RangeError: start offset of Uint32Array should be a multiple of 4` even though I don't use `Uint32Array` anywhere).

**Comment by jtenner** [comment]
@jedisct1 if you can replicate the issue with wasm-crypto, would please help me identify a test that causes it at least?

I don't think that I could handle downloading an entire code base and trace someone else's code all the way back without a little guidance.

**Comment by torch2424** [comment]
Ah yeah I can circle up with @jedisct1 and we can probably come up with a test case together :smile: Definiely agree we could provide more guidance here :+1:

**Comment by jtenner** [comment]
It's definitely a rogue release error related to arrays, and the way to fix it is to find where it lacks a retain. My guess is this might be one of the hardest bugs I'll ever fix in this software.

**Comment by jedisct1** [comment]
Half the wasm-crypto tests exhibit that behavior, and this is actually good news.

That issue is likely to be reproducible using some minimal code they have in common.

I'm working on it. But will that stay relevant with the forthcoming GC changes?

**Comment by jedisct1** [comment]
Ok, problem found, at least for the wasm-crypto case.

That was caused by a class annotated as `@unmanaged` (it's only using `StaticArray`s, but I guess I misunderstood the purpose of `@unmanaged`, and the Rtrace errors didn't show up with previous versions).

**Comment by jtenner** [comment]
I don't believe this is the case. The stack trace clearly shows a refcount decrement in the example above, and @unmanaged classes don't increment or decrement...

**Comment by jedisct1** [comment]
Yeah, this is a bit unexpected, but [that[(https://github.com/jedisct1/wasm-crypto/commit/d02b2c6f53c88997f86940bcb9e0eeff696113ed) really made all the `RTrace` errors go away.

**Comment by torch2424** [comment]
Also just to update this issue: As discussed in the AssemblyScript Meetings: `0.18.x` will use a new runtime, therefore RTrace issues will no longer be relevant on the new runtime :smile: 

So once as-pect updates to the latest runtime whenever it releases, this issue will no longer be relevant :smile: :tada:

**Comment by jtenner** [comment]
This is why I've waited on development. I'm very excited for the new release.

**Comment by jtenner** [comment]
This should be all set.
