### ISSUE TITLE
Overload `==` for a type will cause type error.

### ISSUE THREAD

**Issue by yjhmelody** [jtenner/as-pect#337]
```
ERROR TS2322: Type 'assembly/box/Box<bool>' is not assignable to type 'i32'.

     let equals = i32(actual == expected);
                      ~~~~~~~~~~~~~~~~~~
 in node_modules/@as-pect/assembly/assembly/internal/Expectation.ts(33,22)
```
I define a `Box<T>` type whose `==` return type is `Box<bool>`.

**Comment by yjhmelody** [comment]
Should I always unwrap Box<bool> to comparing them? Or the lib can resolve it?

**Comment by yjhmelody** [comment]
Oh, maybe the `toStrictEqual` can resolve it.

**Comment by jtenner** [comment]
Unwraping a box and comparing it's value makes your test faster. Strict equality is a convenience function, more than it is performant. I might recommending unboxing first.
