### ISSUE TITLE
Support for .as (or other extensions)

### ISSUE THREAD

**Issue by munrocket** [jtenner/as-pect#355]
I am tried to test AS project that uses `.as` extension in source files.
I am solved part of a problem with config
```js
flags: {
  '--extension': [],
  '.as': []
//...
```
But get this error instead
 ```bash
[TestFile.ts] node_modules/@as-pect/assembly/assembly/index.ts --debug --runtime none --extension .as --binaryFile output.wasm --explicitStart --use ASC_RTRACE=1 --exportTable --importMemory --transform /Users/munrocket/code/cg-math/node_modules/@as-pect/core/lib/transform/index.js

ERROR TS6054: File 'node_modules/@as-pect/assembly/assembly/index.ts.as' not found.```
```
This problem probably related to AS compiler, becasue right now we can't mix .as and .ts code (code from as-pect and user code).

**Comment by MaxGraey** [comment]
I guess it should be `"--extension": ".as"`

**Comment by munsocket** [comment]
The problem in compiler itself, he simply can't mix different extensions right now.

**Comment by MaxGraey** [comment]
I think mixing extensions really bad idea. Simple example:
```ts
foo/index.as
foo/index.ts
```
```
import { Foo } from "./foo" // what index should use here?
```

**Comment by munsocket** [comment]
as-pect trying to compile all of them together because it is easier. Probably exist a way how to concat .wasm files but current implementation in as-pect working like that.
```
as-pect/instance.ts
my-project/bar.as
```

**Comment by jtenner** [comment]
If we can't mix extensions, then the entry point for the assembly glue code would have to change extension too. Right? @MaxGraey how can I fix the assembly package to work with as files?

**Comment by MaxGraey** [comment]
> @MaxGraey how can I fix the assembly package to work with as files?

AssemblyScript has a flag for changing default extension. I guess just need read this from asconfig if it present and fallback to `.ts` otherwise. Also you could add same flag for aspect's config

**Comment by munsocket** [comment]
As I know is possible to concat text functions from wasm2wat output. If `assembly` from as-pect simple enougth.
```
wasm2wat as-pect/instance.ts -o file1
wasm2wat my-project/bar.as -o file2
cat file1 file2 >> testfile.wat
wat2wasm test.wat -o test.wasm
```
But It will be slow solution. Another one to change extension in #356
