### ISSUE TITLE
[Feature] Regex via cli

### ISSUE THREAD

**Issue by willemneal** [jtenner/as-pect#40]
Test paths based on passed regex.  This is the default behavior of jest.

Next would be a `-t` flag to filter based on test names not paths.

**Comment by jtenner** [comment]
Yes. I think this should be standardized somehow. Need some time to think about it.

**Comment by willemneal** [comment]
couldn't you just let it override the config's list of included files?

**Comment by jtenner** [comment]
No. This is because include is a glob format, and disclude is a regex format.  Essentially what I need to do is filter the included entry points using a positive match instead of a negative one like disclude does.

**Comment by jtenner** [comment]
Closed now
