### ISSUE TITLE
[Feature] CLI for verbosity

### ISSUE THREAD

**Issue by willemneal** [jtenner/as-pect#41]
By default test output would be the summary of all test suites and then if there is an error be verbose or pass a `--verbose` flag.

**Comment by jtenner** [comment]
No we can just make a new reporter. I'll add it to the command line arguments too.

**Comment by jtenner** [comment]
You can now use in your config:

```ts
import { SummaryTestReporter } from "as-pect";

module.exports = {
  reporter: new SummaryTestReporter(),
};
```

From command line:

```
asp --reporter=SummaryTestReporter
```

This will make your console output look like this:

![image](https://user-images.githubusercontent.com/3761339/56832171-3863cd00-6839-11e9-87ce-63cd8b4ca75e.png)

**Comment by jtenner** [comment]
Please see #42 

Can you please test this branch?

**Comment by willemneal** [comment]
Will do as soon as I’m passing my old tests again ;-)
