### ISSUE TITLE
An expect call outside of a test, but inside of a describe block causes errors.

### ISSUE THREAD

**Issue by willemneal** [jtenner/as-pect#46]
This is more of a note to others to make sure that if you are experiencing errors such as 
```
Cannot read property 'getString' of null
```
make sure you don't have the following:

```ts
describe("statements outside of tests aren't initialized", ()=> {
    expect<string>(var).toStrictlyBe("Hello");
});
```
expect calls needs to be inside a test:
```ts
describe("statements outside of tests aren't initialized", ()=> {
    it("Now the var is initialized by another beforeAll/beforeEach", () => {
        expect<string>(var).toStrictlyBe("Hello");
    });
});
```

**Comment by jtenner** [comment]
Yes. The issue is that expectations outside of test and setup functions will cause the module instantiation to fail.

I will start a pull request tomorrow with the necessary changes for this to produce

```
[Error] There is an expect() function call outside of a test or setup function. The {filename} module will be skipped.
```

Then it will exit code 1.

**Comment by willemneal** [comment]
Awesome!  Nothing like good feedback.

**Comment by jtenner** [comment]
Any news on this? If you tested #47 and it does not break your current test suite, I can merge.
