### ISSUE TITLE
[Feature RFC] Implement reference count reporting 

### ISSUE THREAD

**Issue by jtenner** [jtenner/as-pect#55]
Please use this issue to discuss refcount measurements for testing.

**Comment by jtenner** [comment]
Any thoughts on this @willemneal ?

**Comment by willemneal** [comment]
Yeah we could use [rtrace](https://github.com/AssemblyScript/assemblyscript/tree/master/lib/rtrace)

**Comment by jtenner** [comment]
We settled on a custom reference counting interface that keeps track of increments, decrements, allocations and frees on the latest pull request. There is still more work to do, including documentation, but I'm very proud of the results.

A large code review is needed.
