### ISSUE TITLE
Feature requests: filtering tests by name

### ISSUE THREAD

**Issue by bowenwang1996** [jtenner/as-pect#56]
It would be nice if `as-pect` can filter tests by name like Rust, although since tests usually only have description, we might want to consider some other way of filtering.

**Comment by jtenner** [comment]
The plan for this will be to have `--file=regex` `--test=regex` `--group=regex` flags.

`--file` already exists.

**Comment by jtenner** [comment]
Should be tagged for 1.0.0

**Comment by jtenner** [comment]
Also should support `--files` `--tests` and `--groups`
