### ISSUE TITLE
[Feature] Support Compiler Flags From Command Line

### ISSUE THREAD

**Issue by jtenner** [jtenner/as-pect#60]

**Comment by willemneal** [comment]
To add to this feature, also be able to choose which compiler you want to use.  Not sure how to do this since the compiler's reference is packaged with the compiled js.

**Comment by jtenner** [comment]
I believe it should be a `peerDependency` but I have it as a direct dependency. That should be filed in a separate issue.

**Comment by jtenner** [comment]
I don't know what node.js recommends, but I could simply remove assemblyscript as a dependency at all.

**Comment by jtenner** [comment]
Can we make a parser for this?

I think instead of yargs we should use moo (tokrnizer) and nearley (Earley parser).
