### ISSUE TITLE
custom location for `--init`

### ISSUE THREAD

**Issue by trusktr** [jtenner/as-pect#69]
Hello @jtenner! Just a small one, but I have my source in `src/as/`. It was easy to move the autogenerated stuff out of there, and modify the config file. Might be nice to have an option to specify the source root of the AS files though.

**Comment by jtenner** [comment]
Thanks for the idea.

How about `--init=./src/as`

**Comment by trusktr** [comment]
Looks good

**Comment by jtenner** [comment]
I'm on the fence about this, because I'm pretty sure that the conventions for putting everything in the assembly folder will affect how package management works in the future.

**Comment by trusktr** [comment]
I'm hoping that they don't decide to lock onto specific folders, as it is inflexible (I don't like that about Go).

I think it'd be better if TypeScript adds supports for `.as` extensions (or introduces custom extensions). https://github.com/microsoft/TypeScript/issues/31713

**Comment by jtenner** [comment]
I'm not going to stand up for package management ideas. I will say that aspect is opinionated and I'm just hesitant. It's entirely possible to just move the files yourself :)

**Comment by trusktr** [comment]
> entirely possible to just move the files yourself

Totally. :)

**Comment by willemneal** [comment]
I've been working on package resolution for the mainline compiler and I can say from experience that having them in a separate folder from typescript/javascript makes the most sense.  That is to say, you can call it `src`, but mixing sources is bad, particularly as you pointed out there isn't a unique file extension yet.  Unfortunately, `.as` is ActionScript, and although I'm sure we could still just use it, editors/github will default to use that.

Personally I like having the typescript in the `src` directory as this is what will end up doing the work of loading the wasm.  But WASI and the standardization of loaders will mean that projects can just be assemblyscript source and using the `src` folder makes the most sense.

**Comment by jtenner** [comment]
In your typescript config, there is a top level `"include"` that I keep in every one of my mixed projects.

If you see on the main repo, there is a `typescript.config.json` which contains this line:

```json
{
  "inlude": ["src"]
}
```

This particular line is incredibly helpful. It helps `vscode` separate out what is typescript and what is assemblyscript. This is what I recommend to others.

**Comment by jtenner** [comment]
I've decided to mark this as a `wontfix`, because the philosophy of `as-pect` is to follow a directory structure and pattern.
