### ISSUE TITLE
Reporting Expected and Actual `u64` and `i64` values doesn't work

### ISSUE THREAD

**Issue by jtenner** [jtenner/as-pect#73]
Any advice on the matter @willemneal ?

**Comment by willemneal** [comment]
Perhaps converting them to strings?

**Comment by jtenner** [comment]
Yeah, that would make sense, but the thing is I can get the 8 bytes of information really easily!

```ts
function reportUnsignedBigInt(pointer: number): void {
  pointer >>= 2;
  const result: BigInt = (BigInt(wasm.U32[pointer]) << n32) & BigInt(wasm.U32[pointer + 1]);
  // now result *should* be correct.
}
```

Please correct me if I'm wrong, but I think that signed `i64` values cannot be converted in this way. Also, support for BigInt doesn't appear to be in node 10.

We need to do some kind of feature detection. Right?

**Comment by jtenner** [comment]
This is fixed on the runtime branch. I used the `long` package on npm for this.
