### ISSUE TITLE
testing portable code

### ISSUE THREAD

**Issue by trusktr** [jtenner/as-pect#78]
I'm trying to write portable code that will work in TS/JS. It'd be neat if we could run unit test both in AS and JS. Any ideas?

**Comment by jtenner** [comment]
No. Everything you discover should be through trial and error. Give it a shot and see what happens. The only way to bring light to the darkness is to take a flashlight into the cave.

I am happy to help you come up with solutions for problems you discover.

**Comment by jtenner** [comment]
Just about the only thing I'd say is try using jest with ts-jest for testing. Use the same input globs and use toStrictEqual for object comparison.

**Comment by trusktr** [comment]
> try using jest with ts-jest for testing

I'll probably do something like that. I already have a Karma setup handy.

This was only an idea for as-pect, but maybe not worth it.

I'll share my repo once I have JS tests in place too.

**Comment by jtenner** [comment]
Even aspect tests Javascript code in jest. It mocks the modules using the compiler before the tests and uses snapshots to verify output. Very useful.

Test AS with aspect and use a js framework for your glue :)

**Comment by jtenner** [comment]
@trusktr I plan on adding a "portable" test suite example that runs with the entire `as-pect` testing suite that will be supported for version `2.1.0`.

These tests will be runnable from `jest` (using `ts-jest`) and `as-pect`. Any edge cases that need to be tested should probably be put in these test files.

**Comment by jtenner** [comment]
This was handled. The new `--portable` types allow developers to write portable jest code.
