### ISSUE TITLE
How to add console.log to test source code

### ISSUE THREAD

**Issue by trusktr** [jtenner/as-pect#80]
I'd like to add console.logs inside my code to see what's going on.

In `as-pect.config.js`, I've got

```js
	imports: {
		console: {
			log(msg) {
				console.log(msg)
			},
		},
	},
```

In a `globals.d.ts` file I have

```ts
declare const console: {
	log(a: any): void
}
```

In my AS source I have things like `console.log(whatever)` and my IDE doesn't have any issue with it.

But when I run tests it says

```
ERROR TS2304: Cannot find name 'console'.

                console.log('HELLO --------------------- ')
   ~~~~~~~
```

My `globals.d.ts` is listed in `tsconfig.json`, and it works fine with `asc`.

Is there something I have to do for it to work specifically in `asp`?

**Comment by willemneal** [comment]
There is a log function provided by `as-pect`.  You must provide the type of what is to be logged.  e.g. `log<string>("hello world")`

**Comment by trusktr** [comment]
Ah, good to know.  Unfortunately, the output doesn't appear using `--reporter=SummaryTestReporter`

**Comment by jtenner** [comment]
Yes. This was by design. I can address this with a different kind of reporter.

For now, please switch to the default reporter

**Comment by trusktr** [comment]
The output is too long. Then I could provide a glob at the CLI to test certain tests, but more time consuming.

**Comment by trusktr** [comment]
I re-worded my previous comment, I didn't mean to sound too critical! as-pect is super nice already. :)

**Comment by jtenner** [comment]
One of the problems is that we plan on making the test suite run on separate threads, and console logging output is inextricably linked to the test or group the logging information is in. On separate threads, we can't time logging output, if it gets piped to stdout immediately. 

E. G. It has to be attached to the test object or group object.

**Comment by jtenner** [comment]
You can filter files run using the --file=regex flag. Tests can be filtered with --test and groups with --group

**Comment by trusktr** [comment]
True, but was hoping not to spend more time doing that. I wouldn't mind if output was batched to the bottom of the output, for example.

**Comment by trusktr** [comment]
By the way, when you say threads, are you talking about Node threads or Wasm threads?

**Comment by jtenner** [comment]
Node threads. I have to wait for some compiler optimizations first, but it's on my personal road map.

**Comment by jtenner** [comment]
I have decided that supporting some simple querystring parsing when using the command line options should handle this problem.

This will be addressed in `1.1.0`.

```
module.exports = {
  // the default should be false for backwards compatibility reasons
  reporter: new SummaryTestReporter({ loggingEnabled: true }),
};
```

**Comment by jtenner** [comment]
One last thing @trusktr, being critical of software is something you should never be afraid to speak up about. It means that (most of the time) you either don't understand something or you rightfully point out a responsibility that the developer could pick up. 

This is the latter, and I am happy to assist. Thank you for filing an issue, and please continue to do so.

**Comment by trusktr** [comment]
Cool. Thanks! 🙏 :)
