### ISSUE TITLE
all tests pass, but summary shows a failure

### ISSUE THREAD

**Issue by trusktr** [jtenner/as-pect#82]
I've ran into an interesting case. Here's my output:

```
✔ src/as/glas/core/Layers.spec.ts Pass: 5 / 5 Todo: 0 Time: 4.59ms
✔ src/as/glas2/Math/BezierCurve.spec.ts Pass: 1 / 1 Todo: 0 Time: 0.337ms
✔ src/as/glas2/Math/MathTemp.spec.ts Pass: 0 / 0 Todo: 0 Time: 0.047ms
✔ src/as/glas2/Math/Matrix.spec.ts Pass: 0 / 0 Todo: 0 Time: 0.068ms
✔ src/as/glas2/Math/Quaternion.spec.ts Pass: 0 / 0 Todo: 0 Time: 0.059ms
✔ src/as/glas2/Math/Scalar.spec.ts Pass: 0 / 0 Todo: 0 Time: 0.045ms
✔ src/as/glas2/Math/Size.spec.ts Pass: 12 / 12 Todo: 0 Time: 2.72ms
✔ src/as/glas2/Math/Vector2.spec.ts Pass: 35 / 35 Todo: 0 Time: 8.232ms
✔ src/as/glas2/Math/Vector3.spec.ts Pass: 0 / 0 Todo: 0 Time: 0.044ms
✔ src/as/glas2/Math/Vector4.spec.ts Pass: 0 / 0 Todo: 0 Time: 0.05ms
✔ src/as/glas2/Misc/ArrayTools.spec.ts Pass: 0 / 0 Todo: 0 Time: 0.048ms
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  [Result]: ✖ FAIL
   [Files]: 12 total
  [Groups]: 55 count, 55 pass
   [Tests]: 53 pass, 3 fail, 56 total
    [Time]: 1840.689ms
```

Shows that all tests passed, but the numbers aren't matching in the summary. It does correctly say `53` tests passed, but additionally it says 3 tests failed.

**Comment by trusktr** [comment]
Oops, it's running tests for the glas2 folder, which I didn't intend. I think I goofed something too.

**Comment by trusktr** [comment]
Reproduction:

```sh
git clone git@github.com:infamous/glas.git
cd glas
git checkout as-pect-issue-82
npm i
npm test
```

**Comment by trusktr** [comment]
Update the reproduction, removed a bunch of test files, now the output is minimal:

```
infamous+glas git:master ❯ npm test                                                                                                                                            ✹

> @ test /Users/trusktr/src/infamous+glas
> asp --reporter=SummaryTestReporter

       ___   _____                       __    
      /   | / ___/      ____  ___  _____/ /_   
     / /| | \__ \______/ __ \/ _ \/ ___/ __/   
    / ___ |___/ /_____/ /_/ /  __/ /__/ /_     
   /_/  |_/____/     / .___/\___/\___/\__/     
                    /_/                        

  ⚡AS-pect⚡ Test suite runner [1.0.0-beta]
  
[Log] Using configuration /Users/trusktr/src/infamous+glas/as-pect.config.js
[Log] Including files: src/as/**/*.spec.ts
[Log] Running tests that match: .*
[Log] Running groups that match: .*

✔ src/as/glas/core/Layers.spec.ts Pass: 5 / 5 Todo: 0 Time: 6.027ms
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  [Result]: ✖ FAIL
   [Files]: 2 total
  [Groups]: 7 count, 7 pass
   [Tests]: 5 pass, 3 fail, 8 total
    [Time]: 756.902ms
```

**Comment by trusktr** [comment]
I found that if I delete the `Color.spec.ts` file, then the issue goes away.

**Comment by trusktr** [comment]
Ah, because there's a `describe` in `Color.spec.ts` missing a `test` or `it` block.

Maybe a message can be outputted to help in this case?

**Comment by jtenner** [comment]
Interesting. I can actually fix this problem for the 1.1.0 release. Let me try to reproduce it today.

**Comment by jtenner** [comment]
@trusktr can you do me a favor and isolate the test suite that reports the problem using the default reporter and show me the output?

**Comment by jtenner** [comment]
This may just be a bug in the `SummaryTestReporter`.

**Comment by jtenner** [comment]
Never mind. Please see *this* pull request and use *this* commit to fix your problem: https://github.com/jtenner/as-pect/pull/77/commits/ee8b2ba92a9dfc11202e5f6eb7e52a547081770a

**Comment by trusktr** [comment]
I gave the rtrace branch a shot. I didn't notice a big difference, but I can still reproduce the test failure. In the following reproduction, `Layers.spec.ts` is the only test file. If you restore the comments out lines to restore the `it` block, then the tests will pass:

```sh
git clone git@github.com:infamous/glas.git
cd glas
git checkout as-pect-issue-82-2
npm i
npm test
```

**Comment by trusktr** [comment]
Note, unlike in #81, in this case when disabling the it/test block it doesn't crash with "unreachable", but just silently fails the error; two different outcomes for the same sort of case.

**Comment by jtenner** [comment]
If there are errors or warnings these should now be printed by the SummaryTestReporter.

If this failure is still silent I can try to take a look.
