### ISSUE TITLE
[rtrace] Return the references left in memory after a test or group

### ISSUE THREAD

**Issue by willemneal** [jtenner/as-pect#85]
It would be handy to know which references are left after a test to see what should have been free'd.

**Comment by jtenner** [comment]
Proposed api:

```ts
RTrace.activeTestBlocks(); // return usize[], best used in afterEach() callback
RTrace.activeGroupBlocks(); // returns usize[], best used in afterAll() callback

// and the less usable
RTrace.activeBlocks(); // returns usize[], not sure when this should be used
```

Is this acceptable?

**Comment by willemneal** [comment]
Yeah this will tell you what addresses are left, and you should be able to get the class id to tell you what class the reference is.

**Comment by jtenner** [comment]
There is no classNameOf support yet, but `nameof<T>()` is going to be in the pipeline for assemblyscript at some point.

In the meantime, this issue is completed.
