### ISSUE TITLE
Test filtering doesn't work

### ISSUE THREAD

**Issue by willemneal** [jtenner/as-pect#88]
This is what happens when I try to run use `-t`:
```
~/c/assemblyscript-json  ‹new_runtime*› $ npx asp -f round -t int32
       ___   _____                       __
      /   | / ___/      ____  ___  _____/ /_
     / /| | \__ \______/ __ \/ _ \/ ___/ __/
    / ___ |___/ /_____/ /_/ /  __/ /__/ /_
   /_/  |_/____/     / .___/\___/\___/\__/
                    /_/

  ⚡AS-pect⚡ Test suite runner [1.1.0]


[Log] Initializing types.
```

**Comment by jtenner** [comment]
Take a look for yourself and see what the problem is exactly. I suspect the `-f` and `-t` is being combined into the logical intersection of the two test sets.

**Comment by jtenner** [comment]
Is there a test that matches `int32` that exists in a file that matches `round`?

**Comment by willemneal** [comment]
Two actually.

**Comment by jtenner** [comment]
Actually! Go ahead an inspect the resulting regex.

Chances are that that the regex values are "true" and "true"

**Comment by jtenner** [comment]
Try `-t=int32 -f=round`

**Comment by jtenner** [comment]
In fact, we should probably be parsing the args ourselves. Let's shoot for `1.3.0`
